spring:
  security:
    saml2:
      relyingparty:
        registration:
          one:
            signing.credentials: &rp-metadata
              - private-key-location: classpath:credentials/rp-private.key
                certificate-location: classpath:credentials/rp-certificate.crt
            identityprovider:
              metadata-uri: classpath:metadata.xml
          two:
            signing.credentials: *rp-metadata
            decryption.credentials: *rp-metadata
            identityprovider:
              metadata-uri: classpath:metadata.xml


logging.level:
  org.springframework.security: TRACE
